services:
  db:
    container_name: local_db_kline
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kline_local
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db: