# No services needed; using SQLite file at project root
  db:
    container_name: mysql_db_kline
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: kline_local
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: